print('isalnum')
print("Hello","Hello".isalnum())
print("He o","He o".isalnum())
print('isalpha')
print("Hello","Hello".isalpha())
print("He123","He123".isalpha())
print('isnumeric')
print("123456","123456".isnumeric())
print("He123","He123".isnumeric())
